name: Build ARM64 Python Wheels

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build All Python Libraries for ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t python-arm64-build \
            -f Dockerfile.arm64 \
            --load .

      - name: Run build container and compile libraries
        run: |
          mkdir -p wheels
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}/wheels:/io/wheels \
            python-arm64-build bash -c "
              pip install --upgrade pip &&
              pip wheel \
                numpy scipy pandas matplotlib seaborn scikit-learn scikit-image \
                sympy statsmodels opencv-python pillow tqdm \
                flask django fastapi uvicorn gunicorn \
                tensorflow-cpu tensorflow-lite \
                torch torchvision torchaudio \
                onnx onnxruntime onnxruntime-gpu \
                transformers datasets sentencepiece \
                streamlit gradio plotly dash \
                pyqt5 kivy tk pywebview eel \
                requests beautifulsoup4 lxml \
                openpyxl xlrd xlsxwriter \
                pydantic typer click rich \
                pytest black mypy pylint \
                jupyter jupyterlab \
                -w /io/wheels
            "

      - name: Upload built wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-wheels
          path: wheels/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: arm64-wheels-${{ github.run_number }}
          name: "ARM64 Python Wheels Build #${{ github.run_number }}"
          body: "Prebuilt Python wheels for ARM64 (Top 50 libraries)."
          files: wheels/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
